// Register Your App first
// https://apps.dev.microsoft.com/#/appList

###
# @name get_token

POST https://login.microsoftonline.com/common/oauth2/v2.0/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id={{client_id}}
&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default
&client_secret={{client_secret}}
&grant_type=client_credentials

###
# @name me

GET https://graph.microsoft.com/v1.0/users HTTP/1.1
Authorization: {{get_token.response.body.$.token_type}} {{get_token.response.body.$.access_token}}

###

GET https://graph.microsoft.com/v1.0/users/12345678-73a6-4952-a53a-e9916737ff7f  HTTP/1.1
Authorization: {{get_token.response.body.$.token_type}} {{get_token.response.body.$.access_token}}
